cmake_minimum_required(VERSION 3.31)
project(Lab2 C)

set(CMAKE_C_STANDARD 11)

add_executable(Lab2 main.c
        models/base_house.h
        models/apartment.c
        models/apartment.h
        models/ground_house.c
        models/ground_house.h
        abstract_factory_method/house_creator.c
        abstract_factory_method/house_creator.h
        abstract_factory_method/apartment_creator.c
        abstract_factory_method/apartment_creator.h
        abstract_factory_method/ground_house_creator.c
        abstract_factory_method/ground_house_creator.h
        common/dynamic_array.c
        common/dynamic_array.h
        models/site_999.c
        models/site_999.h
        models/statistics.c
        models/statistics.h
        builder/i_statistics_saver_builder.h
        builder/ro_statistics_saver_builder.c
        builder/ro_statistics_saver_builder.h
        builder/ru_statistics_saver_builder.c
        builder/ru_statistics_saver_builder.h
        builder/en_statistics_saver_builder.c
        builder/en_statistics_saver_builder.h
        builder/statistics_saver_director.c
        builder/statistics_saver_director.h
        defines.h
        common/i_prototype.h
        trash.c
        models/base_house.c
        common/i_as_json.h
        adapter/external_flat_json_adapter.c
        adapter/external_flat_json_adapter.h
        adapter/external_flat.h
        adapter/external_flat_provider.c
        adapter/external_flat_provider.h
        builder/static_statistics_saver_builder.c
        builder/static_statistics_saver_builder.h
        common/i_house_component.h
        models/apartment_building.c
        models/apartment_building.h
        common/dynamic_array_house_component.c
        common/dynamic_array_house_component.h
        models/block_of_apartment_buildings.c
        models/block_of_apartment_buildings.h
        facade/i_house_operations_facade.h
        facade/house_operations_facade.c
        facade/house_operations_facade.h
        decorator/i_apartment_repository.h
        decorator/apartment_repository.c
        decorator/apartment_repository.h
        decorator/app_db_context.c
        decorator/app_db_context.h
        decorator/apartment_repository_logger_decorator.c
        decorator/apartment_repository_logger_decorator.h
        proxy/proxy_base_class.c
        proxy/proxy_base_class.h
        proxy/i_proxy_example.h
        proxy/real_proxy.c
        proxy/real_proxy.h
        bridge/abstraction.c
        bridge/abstraction.h
        bridge/i_abstraction_impl.h
        bridge/macos_abstraction_impl.c
        bridge/macos_abstraction_impl.h
        bridge/concrete_abstraction.c
        bridge/concrete_abstraction.h
        bridge/windows_abstraction_impl.c
        bridge/windows_abstraction_impl.h
        strategy/i_strategy.h
        strategy/concrete_strategy_1.c
        strategy/concrete_strategy_1.h
        strategy/concrete_strategy_2.c
        strategy/concrete_strategy_2.h
        strategy/strategy_context.c
        strategy/strategy_context.h
        common/flyweight_da.c
        common/flyweight_da.h
        flyweight/flyweight.c
        flyweight/flyweight.h
        flyweight/flyweight_context.c
        flyweight/flyweight_context.h
        flyweight/flyweight_factory.c
        flyweight/flyweight_factory.h
        flyweight/flyweight_extrinsic.c
        flyweight/flyweight_extrinsic.h
)
